### ISSUE TITLE
Debian 12 Gnome Breezy wont turn on XR feature

### ISSUE THREAD

**Issue by gboyce1967** [wheaney/breezy-desktop#82]
Good morning,
 I stopped using my Air 2 Ultras for a bit and when I plugged them in they would only work  as a standard display. I tried updating Breezy but it wouldn't complete with the 
./breezy_gnome_setup --tag gnome-44-max option. It errors out saying:
```
Extracting to: /tmp/breezy-gnome-Rc0D3OvV2s/breezy_gnome
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Logs:
```
cat ~/.local/state/breezy_gnome/logs/ui/breezy_desktop.log
2024-12-11 08:06:03,575 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:03,576 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:03,589 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:06:04,577 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:04,577 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:05,578 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:05,578 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:06,578 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:06,579 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:07,579 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:07,579 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:08,580 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:08,580 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:09,581 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:09,581 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:10,582 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:10,582 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:11,583 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:11,583 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:12,584 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:12,584 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:13,585 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:13,585 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:14,586 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:14,586 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:15,587 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:15,587 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:16,588 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:16,588 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:17,588 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:17,588 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:18,589 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:18,589 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:19,590 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:19,590 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:20,591 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:20,591 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:21,591 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:21,592 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:22,593 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:22,593 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:23,593 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:23,593 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:24,594 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:24,594 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:25,595 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:25,595 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:26,596 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:26,596 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:27,597 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:27,597 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:28,597 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:28,597 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:29,598 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:29,598 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:30,600 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:30,600 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:31,600 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:31,600 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:32,601 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:32,601 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:33,602 - breezy_ui - ERROR - Error writing config [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:06:33,602 - breezy_ui - ERROR - Unhandled exception
Traceback (most recent call last):
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 60, in do_set_property
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/configmanager.py", line 54, in _set_breezy_desktop_enabled
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 174, in write_config
  File "/home/gboyce/.local/share/breezydesktop/breezydesktop/xrdriveripc.py", line 166, in write_config
FileNotFoundError: [Errno 2] No such file or directory: 'temp.txt' -> '/home/gboyce/.config/xr_driver/config.ini'
2024-12-11 08:14:43,847 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:14:43,847 - breezy_ui - ERROR - Verification failed
2024-12-11 08:14:44,845 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:14:44,846 - breezy_ui - ERROR - Verification failed
2024-12-11 08:14:45,846 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:14:45,847 - breezy_ui - ERROR - Verification failed
2024-12-11 08:14:47,847 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:14:47,847 - breezy_ui - ERROR - Verification failed
2024-12-11 08:14:48,847 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:14:48,847 - breezy_ui - ERROR - Verification failed
2024-12-11 08:14:50,848 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:14:53,551 - breezy_ui - ERROR - Verification failed
2024-12-11 08:14:56,900 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:14:56,900 - breezy_ui - ERROR - Verification failed
2024-12-11 08:14:59,744 - breezy_ui - ERROR - Could not verify your Breezy GNOME installation. Please ensure that Breezy GNOME is installed.
2024-12-11 08:14:59,744 - breezy_ui - ERROR - Verification failed
```

Thanks for any help you can give!

**Comment by wheaney** [comment]
You'll note that the setup instructions no longer include the `--tag` suggestion since the setup script is now capable of detecting the system requirements prior to downloading the binary, so that's the cause of the problem you're seeing here. I would also recommend deleting the `breezy_gnome_setup` script you have and downloading the latest.

**Comment by gboyce1967** [comment]
Sorry for my late response. Thanks for the help. That took care of it!
